CREATE TABLE transfer_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    operation_id  VARCHAR(255)                            NOT NULL,
    card_from     VARCHAR(255)                            NOT NULL,
    card_to       VARCHAR(255)                            NOT NULL,
    amount        DECIMAL(19, 2)                          NOT NULL,
    fee           DECIMAL(19, 2)                          NOT NULL,
    currency      VARCHAR(255)                            NOT NULL,
    status        SMALLINT                                NOT NULL,
    created_at    TIMESTAMP                               NOT NULL,
    error_message VARCHAR(500),
    CONSTRAINT pk_transfer_logs PRIMARY KEY (id)
);