services:
  #API
  card-transfer-api:
    build:
      context: E:\MyProjects\CardPayment\deploy
      dockerfile: Dockerfile
    image: card-transfer-service:latest
    container_name: card-transfer-api
    ports:
      - "5500:5500"
    environment:
      SERVER_PORT: 5500
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/transferdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      H2_CONSOLE_ENABLED: "true"
      TRANSFER_LOG_FILE: /logs/transfer.log
    volumes:
      - transfer-data:/data
      - transfer-logs:/logs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5500/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - transfer-network
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: "no"
    command:
      - "--web.enable-lifecycle"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  grafana:
      image: grafana/grafana:12.4.2
      restart: "no"
      ports:
        - "3000:3000"
      environment:
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_DISABLE_LOGIN_FORM: "true"
        GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      healthcheck:
        test: curl --fail -s http://localhost:3000/api/health || exit 1
        interval: 10s
        timeout: 5s
        start_period: 10s
        retries: 5

volumes:
  transfer-data:
    driver: local
  transfer-logs:
    driver: local

networks:
  transfer-network:
    driver: bridge